name: Linting - flake8

on:
  pull_request:
    branches:
      - main
      - develop
      - 'feature/**'
  push:
    branches:
      - main
      - develop
      - 'feature/**'
    branches-ignore:
      - 'dependabot/**'

permissions:
  contents: read

jobs:
  linter-flake8:
    name: Linter - flake8
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
          pip install flake8

      - name: Lint with flake8
        run: |
          flake8 . --count --max-complexity=10 --max-line-length=127 --show-source --statistics
